<!doctype html>
<html lang="en">

<head>
	

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="assets/css/bootstrap.min.css">
    <!-- Owl Default CSS -->
    <link rel="stylesheet" href="assets/css/owl.default.min.css">
    <!-- Owl Carousel CSS -->
    <link rel="stylesheet" href="assets/css/owl.carousel.min.css">
    <!-- Owl Magnific CSS -->
    <link rel="stylesheet" href="assets/css/magnific-popup.css">
    <!-- Animate CSS -->
    <link rel="stylesheet" href="assets/css/animate.css">
    <!-- Boxicons CSS -->
    <link rel="stylesheet" href="assets/css/boxicons.min.css">
    <!-- Flaticon CSS -->
    <link rel="stylesheet" href="assets/css/flaticon.css">
    <!-- Meanmenu CSS -->
    <link rel="stylesheet" href="assets/css/meanmenu.css">
    <!-- Nice Select CSS -->
    <link rel="stylesheet" href="assets/css/nice-select.css">
    <!-- Odometer CSS-->
    <link rel="stylesheet" href="assets/css/odometer.css">
    <!-- Style CSS -->
    <link rel="stylesheet" href="assets/css/style.css">
    <!-- Responsive CSS -->
    <link rel="stylesheet" href="assets/css/responsive.css">

    <title>Website Designing Company | Web Designing Company in Delhi</title>
	<meta name="keywords" content="Website Designing Company, website designing companies,web design delhi, web designing company in delhi, about Jaimru Technology">
    </meta>

    <meta name="description" content="Jaimru Technology Pvt Ltd is all about  provide service & support in the Govt & Corporate sector, Know as best Website Designing Company Delhi">
    </meta>

    <link rel="icon" type="image/png" href="assets/img/favicon.png">
	
	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=G-B046SNG251"></script>
	<script>
	  window.dataLayer = window.dataLayer || [];
	  function gtag(){dataLayer.push(arguments);}
	  gtag('js', new Date());

	  gtag('config', 'G-B046SNG251');
	</script>
	
	<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-KPT2D85');</script>
<!-- End Google Tag Manager -->
</head>

<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "Article",
  "name" : "About",
  "author" : {
    "@type" : "Person",
    "name" : "Jaimru Technology Pvt Ltd"
  },
  "datePublished" : "2021-01-15",
  "image" : "https://www.jaimru.com/assets/img/about/about-2.jpg",
  "articleBody" : "Jaimru Technology Pvt Ltd is the group of highly IT professionals in Delhi/NCR. We work to make others life simple with the help of our code and skills. we get the problems first and try to solve them with the IT Solutions which make us best Website Designing Company in Delhi/NCR. Also, it is all about  provide service &amp; support in the Govt &amp; Corporate sector, Know as best website designing company Delhi</P>\n\n                        <DIV class=\"tab about-list-tab\">\n                            <UL class=\"tabs active\">\n                                <LI class=\"current\">\n                                    <A href=\"#\">\n                                        Our History\n                                    </A>\n                                </LI>\n                                <LI>\n                                    <A href=\"#\">\n                                        Our Missinon\n                                    </A>\n                                </LI>\n                                \n                            </UL>\n\n                            <DIV class=\"tab_content\">\n                                <DIV class=\"tabs_item\">\n                                    <DIV class=\"text\">\n                                        <H3>History</H3>\n                                    </DIV>\n\n                                    <P>Jaimru Technology Pvt Ltd is a delhi based IT Professionals in Coding , Designing, Testing and Digital Market experts etc. Jaimru Technology Pvt Ltd is an idea to solve peoples problem and connect them to digital world. With this idea, we (a IT professionals group) started to present our self as a DC(Jaimru Technology Pvt Ltd).",
  "url" : "https://www.jaimru.com/about",
  "publisher" : {
    "@type" : "Organization",
    "name" : "Jaimru Technology Private Limited"
  }
}
</script>

<body>
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-KPT2D85"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->

    <!-- Start Preloader Area -->
    <div class="preloader">
        <div class="preloader">
            <span></span>
            <span></span>
        </div>
    </div>
    <!-- End Preloader Area -->

    <!-- Start Navbar Area -->
    <?php include_once('header.php'); ?>
    <!-- End Navbar Area -->

    <!-- Sidebar Modal -->
    <?php include_once('right-sidebar.php'); ?>
    <!-- End Sidebar Modal -->

    <!-- Start Page Title Area -->
    <div class="page-title-area item-bg-1">
        <div class="d-table">
            <div class="d-table-cell">
                <div class="container">
                    <div class="page-title-content">
                        <h2>About Us</h2>
                        <ul>
                            <li><a href="index">Home</a></li>
                            <li>About</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Page Title Area -->

    <!-- Start About Area -->
    <section class="about-section ptb-100">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-6 p-0">
                    <div class="about-image">
                        <img src="assets/img/about/about-2.jpg" alt="Jaimru-technology-about-image">
                    </div>
                </div>

                <div class="col-lg-6">
                    <div class="about-tab">
                        <h2>About Jaimru Technology Pvt Ltd</h2>
                        <div class="bar"></div>
                        <p style="text-align:justify">Jaimru (JAIMRU TECHNOLOGY PRIVATE LIMITED), an IT Software and Services Company, is one of the few IT companies in India with an exclusive focus on Web Development and IT Services since Jan 15, 2021. Jaimru has highly IT professionals in designing, development and support fields. our team is extremely good to develop a complex design and handle difficult algorithms and providing proper solutions to our clients.
Jaimru provides its IT(Information Technology) services across the world.</p>
						<p style="text-align:justify">We have expertise in design and development in eCommerce Website, Travel Portal, Hotel management, Corporate Website, School/ Institute Website, Government Website with GIGW guidelines, Hospital Website, enterprise resource planning (ERP), Customer relationship management(CRM), Custom Software development, Banking software, Payment gateway integration, REST/SOAP API integration/ development,
providing hosting/server as per client requirement, managing clients running projects and many more.</p>

                        <div class="tab about-list-tab">
                            <ul class="tabs">
                                <li>
                                    <a href="#">
                                        Our History
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        Our Missinon
                                    </a>
                                </li>
                                <!-- <li>
                                    <a href="#">
                                        Friendly Support
                                    </a>
                                </li> -->
                            </ul>

                            <div class="tab_content">
                                <div class="tabs_item">
                                    <div class="text">
                                        <h3>History</h3>
                                    </div>

                                    <p style="text-align:justify">Director of Jaimru Technology Private Limited, Mr Jai Kishor Kashyap has huge experience in IT development and services. After a long journey from a junior developer to IT Head of corporate company's, he decided to start his IT company and He registered Jaimru Technology Private Limited  on 15 January 2021, under Companies Act 1956/2013 of Govt. Of India.  </p>


                                </div>

                                <div class="tabs_item">
                                    <div class="text">
                                        <h3>How to generate your Creative Idea With IT Business</h3>
                                    </div>

                                    <ul class="list">
                                        <li>
                                            <i class="flaticon-tick"></i>
                                            Connect local to digital
                                        </li>

                                        <li>
                                            <i class="flaticon-tick"></i>
                                            Fast Track Your Business
                                        </li>

                                        <li>
                                            <i class="flaticon-tick"></i>
                                            One click reports of online business
                                        </li>

                                        <li>
                                            <i class="flaticon-tick"></i>
                                            Online software pocket friendly for every one
                                        </li>
                                    </ul>


                                </div>

                                <!-- <div class="tabs_item">
                                    <div class="text">
                                        <h3>How to generate your Creative Idea With IT Business</h3>
                                    </div>

                                    <ul class="list">
                                        <li>
                                            <i class="flaticon-tick"></i>
                                            The Philosopy of Business Analytics
                                        </li>

                                        <li>
                                            <i class="flaticon-tick"></i>
                                            Fast Track Your Business
                                        </li>

                                        <li>
                                            <i class="flaticon-tick"></i>
                                            Lies & Damn Lies About Your Business
                                        </li>

                                        <li>
                                            <i class="flaticon-tick"></i>
                                            The Ultimate Deal on Business
                                        </li>
                                    </ul>

                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus commodo viverra maecenas accumsan facilisis.</p>

                                    <a class="default-btn" href="#">
                                        Discover More
                                    </a>
                                </div>  -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- End About Area -->

    <!-- Start Team Area -->

    <!-- End Team Area -->

    <!-- Start Faq Area -->
    <div class="faq-section pb-100">
        <div class="container">
            <div class="section-title">
                <h2>Frequently <span>Asked</span> Questions</h2>
                <p></p>
                <div class="bar"></div>
            </div>


            <div class="row align-items-center">
                <div class="col-lg-6">
                    <div class="faq-accordion">
                        <ul class="accordion">
                            <li class="accordion-item">
                                <a class="accordion-title active" href="javascript:void(0)">
                                    <i class='bx bx-chevron-down'></i>
                                    Does Jaimru Technology Pvt Ltd is registered company?
                                </a>

                                <div class="accordion-content show">
                                    <p>Yes, Jaimru Technology Pvt Ltd is registered under "Company Act 1956/2013" as per India Government Act. </p>
                                </div>
                            </li>

                            <li class="accordion-item">
                                <a class="accordion-title" href="javascript:void(0)">
                                    <i class='bx bx-chevron-down'></i>
                                    Do you work out side of delhi?
                                </a>

                                <div class="accordion-content">
                                    <p>Yes, We provide our services around the world.</p>
                                </div>
                            </li>

                            <li class="accordion-item">
                                <a class="accordion-title" href="javascript:void(0)">
                                    <i class='bx bx-chevron-down'></i>
                                    Does the price go up as my team gets larger?
                                </a>

                                <div class="accordion-content">
                                    <p>No, our product cost very on the modules of software. it does not matter how many team mates are using it.</p>
                                </div>
                            </li>

                            <li class="accordion-item">
                                <a class="accordion-title" href="javascript:void(0)">
                                    <i class='bx bx-chevron-down'></i>
                                    How can I cancel my subscription?
                                </a>

                                <div class="accordion-content">
                                    <p>Anytime you can cancel our services. just need to convery your massege to our represetative.</p>
                                </div>
                            </li>

                            <li class="accordion-item">
                                <a class="accordion-title" href="javascript:void(0)">
                                    <i class='bx bx-chevron-down'></i>
                                    Can I pay via an Invoice?
                                </a>

                                <div class="accordion-content">
                                    <p>Yes, we provide Tax Invoice of our services. you can pay againt that invoice.</p>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>

                <div class="col-lg-6">
                    <div class="faq-image">
                        <img src="assets/img/faq.png" alt="image">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Faq Area -->

    <!-- Start Clients Area -->
    <section class="clients-section pb-100">
        <div class="container">
            <div class="section-title">
                <h2>What Clients Say About Us</h2>
                <p></p>
                <div class="bar"></div>
            </div>

            <div class="clients-slider owl-carousel owl-theme">
                <div class="clients-item">
                    <div class="icon">
                        <i class="flaticon-left-quotes-sign"></i>
                    </div>

                    <p>Mr.Jai was wonderful to work with.He was very patient working with us,very professional,easy to work with and very responsive. i would highly recommend to anyone looking for website design services.</p>

                    <div class="clients-content">
                        <h3>Miss Mona Sharma </h3>
                        <span>Get And Go Himachal</span>
                    </div>
                </div>
				
				<div class="clients-item">
                    <div class="icon">
                        <i class="flaticon-left-quotes-sign"></i>
                    </div>

                    <p>I was looking to design my e-commerce website. Jaimru Technology Pvt Ltd solve my problem and they have given me the website layout option for my e-commerce. its help me to found what I want on my website. I love my website. I am totally thankful to Jaimru Technology Pvt Ltd. keep it good work</p>

                    <div class="clients-content">
                        <h3>Reena Singh</h3>
                        <span>Fashion Designer</span>
                    </div>
                </div>

                <div class="clients-item">
                    <div class="icon">
                        <i class="flaticon-left-quotes-sign"></i>
                    </div>

                    <p>Jaimru Technology Pvt Ltd company developer many software for me all are customised and very useful to me all my manual work is now online. they are just magician they convert my requirement into the software which I want. God Bless You.</p>

                    <div class="clients-content">
                        <h3>Rajiv Verma</h3>
                        <span>Director, Sri Ram Infratech Pvt Ltd</span>
                    </div>
                </div>

                <div class="clients-item">
                    <div class="icon">
                        <i class="flaticon-left-quotes-sign"></i>
                    </div>

                    <p>Thank you Jaimru Technology Pvt Ltd for CRM (Customer Relationship Management) software. my teem love the software and its very easy for me to track them get all reports on page.</p>

                    <div class="clients-content">
                        <h3>Brajmohan Kashyap</h3>
                        <span>Director, Shiv Network Solutions</span>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- End Clients Area -->

    <!-- Start Footer Area -->
    <?php include_once('footer.php'); ?>
    <!-- End Footer Area -->



    <!-- Start Go Top Section -->
    <div class="go-top">
        <i class="bx bx-chevron-up"></i>
        <i class="bx bx-chevron-up"></i>
    </div>
    <!-- End Go Top Section -->

    <!-- Jquery Slim JS -->
    <script src="assets/js/jquery.min.js"></script>
    <!-- Popper JS -->
    <script src="assets/js/popper.min.js"></script>
    <!-- Bootstrap JS -->
    <script src="assets/js/bootstrap.min.js"></script>
    <!-- Meanmenu JS -->
    <script src="assets/js/jquery.meanmenu.js"></script>
    <!-- Owl Carousel JS -->
    <script src="assets/js/owl.carousel.js"></script>
    <!-- Owl Magnific JS -->
    <script src="assets/js/jquery.magnific-popup.min.js"></script>
    <!-- Nice Select JS -->
    <script src="assets/js/jquery.nice-select.min.js"></script>
    <!-- Appear JS -->
    <script src="assets/js/jquery.appear.js"></script>
    <!-- Odometer JS -->
    <script src="assets/js/odometer.min.js"></script>
    <!-- Form Ajaxchimp JS -->
    <script src="assets/js/jquery.ajaxchimp.min.js"></script>
    <!-- Form Validator JS -->
    <script src="assets/js/form-validator.min.js"></script>
    <!-- Contact JS -->
    <script src="assets/js/contact-form-script.js"></script>
    <!-- Wow JS -->
    <script src="assets/js/wow.min.js"></script>
    <!-- Custom JS -->
    <script src="assets/js/main.js"></script>
</body>



</html>